<script setup>
import {
  Activity,
  ArrowDownLeft,
  ArrowDownToLine,
  ArrowRight,
  ArrowUpRight,
  ArrowLeftRight,
  AudioLines,
  Box,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Code2,
  Copy,
  Cpu,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  Filter,
  Gauge,
  Globe2,
  Grid2X2,
  KeyRound,
  Layers3,
  LayoutDashboard,
  List,
  LoaderCircle,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Terminal,
  Trash2,
  Upload,
  Users,
  Workflow,
  X,
  XCircle,
  Zap,
  AlertCircle,
  CheckCircle2,
  Circle,
  Command,
} from "lucide-vue-next";
defineProps({
  name: { type: String, default: "activity" },
  size: { type: [Number, String], default: 18 },
});
const icons = {
  activity: Activity,
  arrowDownLeft: ArrowDownLeft,
  download: ArrowDownToLine,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  switch: ArrowLeftRight,
  audio: AudioLines,
  box: Box,
  calendar: CalendarDays,
  check: Check,
  checks: CheckCheck,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  help: CircleHelp,
  clock: Clock3,
  code: Code2,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  file: FileJson,
  filter: Filter,
  gauge: Gauge,
  globe: Globe2,
  grid: Grid2X2,
  key: KeyRound,
  layers: Layers3,
  dashboard: LayoutDashboard,
  list: List,
  loading: LoaderCircle,
  logout: LogOut,
  menu: Menu,
  moon: Moon,
  more: MoreHorizontal,
  pause: Pause,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  upload: Upload,
  users: Users,
  workflow: Workflow,
  x: X,
  error: XCircle,
  zap: Zap,
  alert: AlertCircle,
  success: CheckCircle2,
  circle: Circle,
  command: Command,
};
</script>
<template>
  <component
    :is="icons[name] || Activity"
    :size="size"
    :stroke-width="1.65"
    aria-hidden="true"
  />
</template>
